eureka:
  client:
    serviceUrl:
      defaultZone: http://admin:123456@192.168.56.122:8761/eureka/

server:
  port: 8777
  
spring:
  application:
    name: eshop-one-service
    
feign: 
  hystrix:
    enabled: true